name: Create Release Package [public]

# Define the triggers for this workflow
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  # Get environment variable for docker image URI and provide it to next build step
  prep-linux:
    runs-on: [ubuntu-22.04]
    outputs:
      image: ${{ steps.set_image.outputs.image }}
    environment: build-action
    steps:
      - id: set_image
        env: 
          DOCKER_IMAGE_URI: ${{ vars.DOCKER_IMAGE_URI }} 
        run: echo "image=${{vars.DOCKER_IMAGE_URI}}" >> "$GITHUB_OUTPUT"


  # Build the project, then remove the built artifacts
  build-linux:
    runs-on: [ubuntu-22.04]
    needs: prep-linux
    container:
      image: ${{ needs.prep-linux.outputs.image }}
    steps:
    # Check out this Git repo
    - uses: actions/checkout@v4
    - name: Build & Publish
      run: dotnet build ./FmuImporter/BuildAll/Build.csproj -v:m
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        draft: true
        files: |
          ./FmuImporter/_publish/SilKitFmuImporter-*-xPlatform-x64.zip
