name: Repo sync

on:
  workflow_run:
    workflows: ["Build the SIL Kit FMU Importer (.NET 6) (internal)"]
    types:
      - completed

jobs:
  sync_main_branch:
    name: Sync branch to remote public GitHub
    runs-on: 
      - Linux
      - Small
    environment: repo-sync-action/public-github
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0
      - uses: vector-actions/repo-sync-action@main
        with:
          app-key:          ${{ secrets.APP_KEY }}
          app-id:           ${{ secrets.APP_ID }}
          remote-repo-url:  ${{ secrets.REMOTE_REPO_URL }}
          remote-branch:    ${{ secrets.REMOTE_BRANCH }}
          local-branch:     origin/main